#! /bin/bash
# ДЗ Павлов Алексей.
echo "Ne pustoy" > /tmp/file.txt # Первый не пустой файл
cal > /tmp/file2.txt # Второй не пустой файл
date > /tmp/file3.txt # Третий не пустой файл
root@x.x.x.x 'mkdir /root/backup/' # Создаем папку на удаленном сервере
rsync -avz /tmp/file.txt /tmp/file2.txt /tmp/file3.txt root@x.x.x.x:/root/backup # Копируем файлы в удаленную папку
root@x.x.x.x 'find /root/backup* -mtime +7 -exec rm {} \;' # Находим и удаляем файлы старше 7 дней
